import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { HeaderComponent } from '../src/components/Header'
import { HomeComponent } from '../src/components/Home'
import { AboutComponent } from '../src/components/About'
import { ExperienceComponent } from '../src/components/Experience'
import { ProjectsComponent } from '../src/components/Projects'
import { ContactComponent } from '../src/components/Contact'
import { FooterComponent } from '../src/components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500&family=Poppins:wght@700&display=swap');
        </style>
        <title>Portfolio Guilherme Lawisch Machado</title>
      </Head>

      <main className={styles.main}>
        <HeaderComponent/>

        <HomeComponent/>
        <div className={styles.dividerRight}></div>

        <AboutComponent/>
        <div className={styles.dividerLeft}></div>

        <ExperienceComponent/>
        <div className={styles.dividerRight}></div>

        <ProjectsComponent/>
        <div className={styles.dividerLeft}></div>

        <ContactComponent/>

        <FooterComponent/>
      </main>
    </div>
  )
}
