import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { HeaderComponent } from '../src/components/Header'
import { HomeComponent } from '../src/components/Home'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500&family=Poppins:wght@700&display=swap');
        </style>
      </Head>

      <main className={styles.main}>
        <HeaderComponent/>

        <HomeComponent/>
        <div className={styles.dividerRight}></div>

        <h1>Sobre Guilherme Lawisch Machado</h1>
      </main>
    </div>
  )
}
